create table potions
(
    potion_id bigint generated by default as identity primary key,
    potion_no int          not null,
    name      varchar(200) not null,
    constraint uq_potions_potion_no unique (potion_no)
);

create table ingredients
(
    ingredient_id bigint generated by default as identity primary key,
    name          varchar(200) not null,
    constraint uq_ingredients_name unique (name)
);

create table potion_ingredients
(
    potion_id     bigint not null,
    ingredient_id bigint not null,
    qty           int    not null,
    constraint pk_potion_ingredients primary key (potion_id, ingredient_id),
    constraint fk_pi_potion foreign key (potion_id) references potions (potion_id) on delete cascade,
    constraint fk_pi_ingredient foreign key (ingredient_id) references ingredients (ingredient_id),
    constraint ck_pi_qty_positive check (qty > 0)
);

create table instruction_variants
(
    variant_id bigint generated by default as identity primary key,
    potion_id  bigint       not null,
    label      varchar(100) not null,
    constraint fk_iv_potion foreign key (potion_id) references potions (potion_id) on delete cascade,
    constraint uq_iv_potion_label unique (potion_id, label)
);

create table instruction_steps
(
    variant_id bigint not null,
    step_no    int    not null,
    step_text  clob   not null,
    constraint pk_instruction_steps primary key (variant_id, step_no),
    constraint fk_is_variant foreign key (variant_id) references instruction_variants (variant_id) on delete cascade,
    constraint ck_is_step_no_positive check (step_no > 0)
);

create table potion_effects
(
    potion_id   bigint      not null,
    quality     varchar(50) not null,
    effect_text clob        not null,
    constraint pk_potion_effects primary key (potion_id, quality),
    constraint fk_pe_potion foreign key (potion_id) references potions (potion_id) on delete cascade
);

create table potion_quantity_requirements
(
    potion_id      bigint       not null,
    perk_tier      varchar(120) not null,
    required_count int          not null,
    constraint pk_potion_quantity primary key (potion_id, perk_tier),
    constraint fk_pqr_potion foreign key (potion_id) references potions (potion_id) on delete cascade,
    constraint ck_pqr_required_count_nonneg check (required_count >= 0)
);